on: [push]

name: build

jobs:
  build:
    name: Build aws ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: python-alpine
        image-name: aws-ci 
        tags: latest alpine 1.0.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
